[workspace]
authors = ["jsakatsume"]
channels = ["conda-forge"]
name = "ds-hdp-hmm"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = "*"
ruff = "*"
pyrefly = "*"
pre-commit = "*"

[feature.py36]
platforms = ["linux-64"]

[feature.py36.dependencies]
python = "3.6.*"
numpy = ">=1.19.5,<2"
scipy = ">=1.5.3,<2"
matplotlib = ">=3.3.4,<4"
munkres = ">=1.1.4,<2"

[feature.py312]
platforms = ["linux-64", "osx-arm64"]

[feature.py312.dependencies]
python = "3.12.*"
numpy = ">=2.4.0,<3"
scipy = ">=1.16.3,<2"
matplotlib = ">=3.10.8,<4"
munkres = ">=1.1.4,<2"

[environments]
default = ["py312"]
py36 = ["py36"]
