[workspace]
authors = ["jsakatsume"]
channels = ["conda-forge"]
name = "ds-hdp-hmm"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
jupyterlab = "*"
ruff = "*"
pyrefly = "*"
pre-commit = "*"
hmms = { path = "."}

[feature.py312]
platforms = ["linux-64", "osx-arm64"]

[feature.py312.dependencies]
python = "3.12.*"
numpy = ">=2.4.0,<3"
scipy = ">=1.16.3,<2"
matplotlib = ">=3.10.8,<4"
munkres = ">=1.1.4,<2"

[environments]
default = ["py312"]

[package] 
name = "hmms"
version = "0.1.0"

[package.build] 
backend = { name = "pixi-build-python", version = "==0.4.0" }

[package.host-dependencies] 
hatchling = "==1.26.3"

[package.run-dependencies] 
python = "3.12.*"
numpy = ">=2.4.0,<3"
scipy = ">=1.16.3,<2"
matplotlib = ">=3.10.8,<4"
munkres = ">=1.1.4,<2"
