[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hmms"
version = "0.1.0"
requires-python = ">=3.12,<3.13"

dependencies = [
	"numpy>=2.4.0,<3",
	"scipy>=1.16.3,<2",
	"matplotlib>=3.10.8,<4",
	"munkres>=1.1.4,<2",
]
